name = "secure-redirect-landing"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "secure-redirect-landing-prod"

[env.staging]
name = "secure-redirect-landing-staging"

# KV Namespaces for enhanced rate limiting and analytics
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "your-rate-limit-kv-id"
preview_id = "your-preview-rate-limit-kv-id" 