name = "secure-redirect-landing"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "secure-redirect-landing-prod"

[env.staging]
name = "secure-redirect-landing-staging"

# KV Namespaces for enhanced rate limiting and analytics
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "ba383042bdf947ada2c551898fcbb3f8"
preview_id = "ba383042bdf947ada2c551898fcbb3f8" 